# Generated by Django 5.0.7 on 2024-07-17 12:27

import compartytion.utils
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnauthenticatedUser",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "otp",
                    models.TextField(
                        default=compartytion.utils.generate_otp,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OTP는 반드시 6자로 입력되어야 합니다.",
                                regex="^[0-9]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "인증되지 않은 사용자",
                "verbose_name_plural": "인증되지 않은 사용자들",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일 주소"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "이미 존재하는 사용자명입니다."},
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                regex="[a-zA-Z가-힣0-9_\\-]+"
                            ),
                        ],
                        verbose_name="사용자명",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="관리자 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="가입 일자",
                    ),
                ),
                (
                    "last_password_changed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="최근 비밀번호 변경일",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "계정",
                "verbose_name_plural": "계정들",
            },
        ),
    ]
