# Generated by Django 5.0.7 on 2024-07-23 17:27

import compartytion.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True,
                        upload_to=compartytion.users.models.avatar_directory_path,
                        verbose_name="프로필 사진",
                    ),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="소개")),
            ],
            options={
                "verbose_name": "프로필",
                "verbose_name_plural": "프로필들",
            },
        ),
    ]
