# Generated by Django 5.0.7 on 2024-07-27 16:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="displayed_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hidden_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
    ]
