# Generated by Django 5.0.7 on 2024-07-29 08:14

import compartytion.users.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="displayed_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="공개 이름",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hidden_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="비공개 이름",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to=compartytion.users.models.avatar_directory_path,
                verbose_name="아바타",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, max_length=255, verbose_name="소개"),
        ),
    ]
