version: "1.0"

services:
  postgres:
    image: postgres:15
    restart: "on-failure"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=compartytion
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - TZ=Asia/Seoul
