# Generated by Django 5.1.2 on 2024-11-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="applicant",
            name="unique_access_id_applicant",
        ),
        migrations.RemoveConstraint(
            model_name="participant",
            name="unique_access_id_participant",
        ),
    ]
